// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PraiApp.Repository;

#nullable disable

namespace PraiApp.Migrations
{
    [DbContext(typeof(PraiAppContext))]
    partial class PraiAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PraiApp.Models.AvaliacaoModel", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AVALIACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<double>("ConservacaoAvaliacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CONSERVACAO_AMBIENTAL_AVALIACAO");

                    b.Property<double>("EstruturaAvaliacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("ESTRUTURA_AVALIACAO");

                    b.Property<long>("IdPraia")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("IdUser")
                        .HasColumnType("NUMBER(19)");

                    b.Property<double>("LimpezaAvaliacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LIMPEZA_AVALIACAO");

                    b.Property<double>("MonitoramentoAvaliacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("MONITORAMENTO_AVALIACAO");

                    b.Property<double>("PoluicaoAvaliacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("POLUICAO_AVALIACAO");

                    b.Property<double>("SinalizacaoAvaliacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("SINALIZACAO_AVALIACAO");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdPraia");

                    b.HasIndex("IdUser");

                    b.ToTable("TBL_AVALIACAO");
                });

            modelBuilder.Entity("PraiApp.Models.EnderecoModel", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("CepEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cep_endereco");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade_endereco");

                    b.Property<string>("RuaEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("rua_endereco");

                    b.Property<string>("UfEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("uf_endereco");

                    b.HasKey("IdEndereco");

                    b.ToTable("TBL_ENDERECO");
                });

            modelBuilder.Entity("PraiApp.Models.OrganizacaoModel", b =>
                {
                    b.Property<long>("IdOrganizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ORGANIZACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdOrganizacao"));

                    b.Property<string>("CnpjOrganizacao")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CNPJ_ORGANIZACAO");

                    b.Property<string>("DescricaoOrganizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESC_ORGANIZACAO");

                    b.Property<int>("IdEndereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeOrganizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_ORGANIZACAO");

                    b.Property<string>("TipoOrganizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TP_ORGANIZACAO");

                    b.HasKey("IdOrganizacao");

                    b.HasIndex("IdEndereco");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("TBL_ORGANIZACAO");
                });

            modelBuilder.Entity("PraiApp.Models.PraiaModel", b =>
                {
                    b.Property<long>("IdPraia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PRAIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPraia"));

                    b.Property<string>("DescPraia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESC_PRAIA");

                    b.Property<int>("IdEndereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomePraia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_PRAIA");

                    b.Property<double>("TotConservacaoPraia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CONSERVACAO_AMBIENTAL_PRAIA");

                    b.Property<double>("TotEstruturaPraia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("ESTRUTURA_PRAIA");

                    b.Property<double>("TotLimpezaPraia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LIMPEZA_PRAIA");

                    b.Property<double>("TotMonitoramentoPraia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("MONITORAMENTO_PRAIA");

                    b.Property<double>("TotPoluicaoPraia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("POLUICAO_PRAIA");

                    b.Property<double>("TotSinalizacaoPraia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("SINALIZACAO_PRAIA");

                    b.Property<double>("TotalPraia")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("TOTAL_PRAIA");

                    b.HasKey("IdPraia");

                    b.HasIndex("IdEndereco");

                    b.ToTable("TBL_PRAIA");
                });

            modelBuilder.Entity("PraiApp.Models.ResponsavelModel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_responsavel");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResponsavel"));

                    b.Property<string>("CpfResponsavel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("CPF_RESPONSAVEL");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_responsavel");

                    b.HasKey("IdResponsavel");

                    b.ToTable("TBL_RESPONSAVEL");
                });

            modelBuilder.Entity("PraiApp.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL_USER");

                    b.Property<long>("IdOrganizacao")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_USER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA_USER");

                    b.HasKey("Id");

                    b.HasIndex("IdOrganizacao");

                    b.ToTable("TBL_USER");
                });

            modelBuilder.Entity("PraiApp.Models.AvaliacaoModel", b =>
                {
                    b.HasOne("PraiApp.Models.PraiaModel", "Praia")
                        .WithMany()
                        .HasForeignKey("IdPraia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PraiApp.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Praia");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PraiApp.Models.OrganizacaoModel", b =>
                {
                    b.HasOne("PraiApp.Models.EnderecoModel", "Endereco")
                        .WithMany("Organizacoes")
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PraiApp.Models.ResponsavelModel", "Responsavel")
                        .WithMany("Organizacoes")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("PraiApp.Models.PraiaModel", b =>
                {
                    b.HasOne("PraiApp.Models.EnderecoModel", "Endereco")
                        .WithMany()
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PraiApp.Models.UserModel", b =>
                {
                    b.HasOne("PraiApp.Models.OrganizacaoModel", "Organizacao")
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacao");
                });

            modelBuilder.Entity("PraiApp.Models.EnderecoModel", b =>
                {
                    b.Navigation("Organizacoes");
                });

            modelBuilder.Entity("PraiApp.Models.ResponsavelModel", b =>
                {
                    b.Navigation("Organizacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
